'use strict';
const ChaosSort=(()=>{
const catalog=[];
function add(name,family,config={},note=''){catalog.push({id:catalog.length,name,family,config,note});}
add('Bubble','Bubble');add('Bubble · early exit','Bubble',{early:true});add('Bubble · backward','Bubble',{reverse:true});add('Bubble · recursive','Bubble',{recursive:true});
add('Cocktail shaker','Cocktail');add('Cocktail · early exit','Cocktail',{early:true});
for(const gap of [1.2,1.25,1.3,1.5])add('Comb · shrink '+gap,'Comb',{gap});
add('Gnome','Gnome');add('Gnome · smart restart','Gnome',{smart:true});add('Odd–even','Odd-even');add('Odd–even · even first','Odd-even',{even:true});
add('Selection','Selection');add('Stable selection','Selection',{stable:true});add('Double selection','Selection',{double:true});add('Cycle','Cycle');
add('Insertion','Insertion');add('Binary insertion','Insertion',{binary:true});add('Insertion · recursive','Insertion',{recursive:true});add('Insertion · right to left','Insertion',{reverse:true});add('Insertion · adjacent swaps','Insertion',{swaps:true});
for(const sequence of ['Shell','Hibbard','Knuth','Ciura','Tokuda','Pratt','Sedgewick','Powers of 3','Fibonacci','Odd halves'])add('Shell · '+sequence,'Shell',{sequence},'Shellsort variant with '+sequence+' gap sequence.');
for(const tree of ['Unbalanced','AVL','Treap','Splay'])add(tree+' tree sort','Tree',{tree});add('Patience','Patience');
for(const pivot of ['First','Last','Middle','Random','Median of 3'])for(const partition of ['Lomuto','Hoare','Three-way','Intro'])add((partition==='Intro'?'Introsort':'Quick · '+partition)+' / '+pivot,'Quick',{pivot,partition},partition==='Intro'?'Quicksort with insertion cutoff and heap fallback at the depth limit.':'Quicksort variant: '+partition+' partition, '+pivot.toLowerCase()+' pivot.');
add('Merge · top down','Merge');add('Merge · bottom up','Merge',{bottom:true});add('Natural merge','Merge',{natural:true});add('Merge · skip ordered','Merge',{skip:true});add('Merge · insertion cutoff 8','Merge',{cutoff:8});add('Merge · insertion cutoff 16','Merge',{cutoff:16});add('Merge · three way','Merge',{ways:3});add('Merge · four way','Merge',{ways:4});
for(const arity of [2,3,4,8]){add('Heap · '+arity+'-ary / Floyd build','Heap',{arity});add('Heap · '+arity+'-ary / insertion build','Heap',{arity,insert:true});}
add('Counting','Counting');for(const buckets of [2,4,8,16])add('Bucket · '+buckets+' buckets','Bucket',{buckets});
for(const base of [2,4,10,16]){add('LSD radix · base '+base,'Radix',{base});add('MSD radix · base '+base,'Radix',{base,msd:true});}
add('American flag · base 10','American flag',{base:10});add('Bead','Bead');add('Bitonic network','Bitonic');add('Odd–even merge network','Network');add('Pancake','Pancake');add('Stooge','Stooge');add('Slow sort','Slow');add('Bogo','Bogo');add('Random swap sort','Random swap');add('Bogobogo','Bogobogo');
add('Strand','Strand');add('Pigeonhole','Pigeonhole');add('Tournament','Tournament');
// Parameter variants are explicitly named; each changes the executable strategy.
for(let base=2;base<=64;base++){if(![2,4,10,16].includes(base)){add('LSD radix · base '+base,'Radix',{base});add('MSD radix · base '+base,'Radix',{base,msd:true});}}
for(let base=2;base<=64;base++)if(base!==10)add('American flag · base '+base,'American flag',{base});
for(let arity=2;arity<=32;arity++)if(![2,3,4,8].includes(arity)){add('Heap · '+arity+'-ary / Floyd build','Heap',{arity});add('Heap · '+arity+'-ary / insertion build','Heap',{arity,insert:true});}
for(let buckets=2;buckets<=64;buckets++)if(![2,4,8,16].includes(buckets))add('Bucket · '+buckets+' buckets','Bucket',{buckets});
for(let ways=5;ways<=20;ways++)add('Merge · '+ways+' way','Merge',{ways});
for(let cutoff=2;cutoff<=32;cutoff++)if(![8,16].includes(cutoff))add('Merge · insertion cutoff '+cutoff,'Merge',{cutoff});
for(const pivot of ['First','Last','Middle','Random','Median of 3'])for(const cutoff of [2,4,8,16,24,32,48,64])add('Introsort / '+pivot+' / cutoff '+cutoff,'Quick',{pivot,partition:'Intro',cutoff},'Introsort variant: '+pivot.toLowerCase()+' pivot, insertion cutoff '+cutoff+', and heap fallback at the depth limit.');
for(const shrink of [1.1,1.15,1.35,1.4,1.45,1.55,1.6,1.65,1.7,1.75,1.8,1.85,1.9,1.95,2,2.1,2.2,2.3,2.4,2.5,2.6,2.7])add('Comb · shrink '+shrink,'Comb',{gap:shrink});
function random(seed){let n=seed>>>0;return()=>{n+=0x6D2B79F5;let t=n;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function input(seed,size,pattern){const r=random(seed);let a=Array.from({length:size},()=>1+Math.floor(r()*99));if(pattern==='reverse')a.sort((a,b)=>b-a);if(pattern==='sorted')a.sort((a,b)=>a-b);if(pattern==='almost'){a.sort((a,b)=>a-b);for(let i=0;i<Math.max(1,size/16);i++){const x=Math.floor(r()*size),y=Math.floor(r()*size);[a[x],a[y]]=[a[y],a[x]];}}if(pattern==='duplicates')a=a.map(v=>1+v%5*20);if(pattern==='mountain'){a.sort((a,b)=>a-b);a=a.filter((_,i)=>i%2===0).concat(a.filter((_,i)=>i%2===1).reverse());}return a;}
function racer(entry,values,seed=1337,limit=100000){const a=values.slice(),n=a.length,c=entry.config,r=random(seed+entry.id),s={a,active:[],ops:0,comparisons:0,writes:0,done:false,capped:false,error:'',finish:null};
function* compare(i,j){s.comparisons++;s.ops++;s.active=[i,j];yield;return a[i]-a[j];}
function* valueCompare(x,y,i=-1,j=-1){s.comparisons++;s.ops++;s.active=[i,j];yield;return x-y;}
function* swap(i,j){if(i===j)return;[a[i],a[j]]=[a[j],a[i]];s.writes+=2;s.ops++;s.active=[i,j];yield;}
function* write(i,v){a[i]=v;s.writes++;s.ops++;s.active=[i];yield;}
function* aux(){s.ops++;s.active=[];yield;}
function* insertion(lo=0,hi=n,gap=1){for(let i=lo+gap;i<hi;i++){const v=a[i];let j=i-gap;if(c.binary&&gap===1){let l=lo,h=i;while(l<h){let m=(l+h)>>1;if((yield* valueCompare(a[m],v,m,i))<=0)l=m+1;else h=m;}for(let k=i;k>l;k--)yield* write(k,a[k-1]);yield* write(l,v);}else if(c.swaps){while(j>=lo&&(yield* compare(j,j+gap))>0){yield* swap(j,j+gap);j-=gap;}}else{while(j>=lo&&(yield* valueCompare(a[j],v,j,i))>0){yield* write(j+gap,a[j]);j-=gap;}yield* write(j+gap,v);}}}
function* heap(lo=0,hi=n){const size=hi-lo,d=c.arity||2;function* down(i,end){while(d*i+1<end){let k=d*i+1;for(let j=k+1;j<Math.min(d*i+d+1,end);j++)if((yield* compare(lo+j,lo+k))>0)k=j;if((yield* compare(lo+i,lo+k))>=0)break;yield* swap(lo+i,lo+k);i=k;}}
if(c.insert){for(let i=1;i<size;i++){let j=i;while(j>0){const p=Math.floor((j-1)/d);if((yield* compare(lo+j,lo+p))<=0)break;yield* swap(lo+j,lo+p);j=p;}}}else for(let i=Math.floor((size-2)/d);i>=0;i--)yield* down(i,size);for(let end=size-1;end>0;end--){yield* swap(lo,lo+end);yield* down(0,end);}}
function* quick(lo,hi,depth=0){if(lo>=hi)return;if(c.partition==='Intro'){if(hi-lo<(c.cutoff||12)){yield* insertion(lo,hi+1);return;}if(depth>2*Math.floor(Math.log2(n))){yield* heap(lo,hi+1);return;}}let p=c.pivot==='First'?lo:c.pivot==='Middle'?(lo+hi)>>1:c.pivot==='Random'?lo+Math.floor(r()*(hi-lo+1)):hi;if(c.pivot==='Median of 3'){const ids=[lo,(lo+hi)>>1,hi];if((yield* compare(ids[0],ids[1]))>0)[ids[0],ids[1]]=[ids[1],ids[0]];if((yield* compare(ids[1],ids[2]))>0)[ids[1],ids[2]]=[ids[2],ids[1]];if((yield* compare(ids[0],ids[1]))>0)[ids[0],ids[1]]=[ids[1],ids[0]];p=ids[1];}const pivot=a[p];
if(c.partition==='Hoare'){let i=lo-1,j=hi+1;while(true){do{i++;}while((yield* valueCompare(a[i],pivot,i,p))<0);do{j--;}while((yield* valueCompare(a[j],pivot,j,p))>0);if(i>=j){if(j===hi)j--;yield* quick(lo,j,depth+1);yield* quick(j+1,hi,depth+1);return;}yield* swap(i,j);}}
else if(c.partition==='Three-way'){let l=lo,i=lo,h=hi;while(i<=h){const d=yield* valueCompare(a[i],pivot,i,p);if(d<0){yield* swap(l++,i++);}else if(d>0){yield* swap(i,h--);}else i++;}yield* quick(lo,l-1,depth+1);yield* quick(h+1,hi,depth+1);}
else{yield* swap(p,hi);let k=lo;for(let i=lo;i<hi;i++)if((yield* compare(i,hi))<0)yield* swap(i,k++);yield* swap(k,hi);yield* quick(lo,k-1,depth+1);yield* quick(k+1,hi,depth+1);}}
function* mergeSegments(bounds){const ends=bounds.slice(1),pos=bounds.slice(0,-1),out=[];while(out.length<bounds.at(-1)-bounds[0]){let best=-1;for(let j=0;j<pos.length;j++)if(pos[j]<ends[j]&&(best<0||(yield* compare(pos[j],pos[best]))<0))best=j;out.push(a[pos[best]++]);yield* aux();}for(let i=0;i<out.length;i++)yield* write(bounds[0]+i,out[i]);}
function* merge(lo,hi){if(hi-lo<2)return;if(c.cutoff&&hi-lo<=c.cutoff){yield* insertion(lo,hi);return;}const ways=Math.min(c.ways||2,hi-lo),bounds=[lo];for(let k=1;k<=ways;k++)bounds.push(lo+Math.floor((hi-lo)*k/ways));for(let k=0;k<ways;k++)yield* merge(bounds[k],bounds[k+1]);if(c.skip&&(yield* compare(bounds[1]-1,bounds[1]))<=0)return;yield* mergeSegments(bounds);}
function* flip(end){for(let i=0;i<end-i;i++)yield* swap(i,end-i);}
function* treeSort(){let root=null;const nodes=[];function height(t){return t?t.h:0;}function fix(t){if(t)t.h=1+Math.max(height(t.l),height(t.r));return t;}function right(t){const u=t.l;t.l=u.r;u.r=fix(t);return fix(u);}function left(t){const u=t.r;t.r=u.l;u.l=fix(t);return fix(u);}
function* insert(t,node){if(!t){yield* aux();return node;}const diff=yield* valueCompare(node.v,t.v,node.idx,t.idx);if(diff<0)t.l=yield* insert(t.l,node);else t.r=yield* insert(t.r,node);fix(t);if(c.tree==='AVL'){const balance=height(t.l)-height(t.r);if(balance>1){if(height(t.l.l)<height(t.l.r))t.l=left(t.l);yield* aux();return right(t);}if(balance< -1){if(height(t.r.r)<height(t.r.l))t.r=right(t.r);yield* aux();return left(t);}}if(c.tree==='Treap'){if(t.l&&t.l.priority<t.priority){yield* aux();return right(t);}if(t.r&&t.r.priority<t.priority){yield* aux();return left(t);}}return t;}
function* splay(t,v,idx){if(!t)return t;const diff=yield* valueCompare(v,t.v,idx,t.idx);if(diff<0){if(!t.l)return t;const d=yield* valueCompare(v,t.l.v,idx,t.l.idx);if(d<0){t.l.l=yield* splay(t.l.l,v,idx);t=right(t);}else if(d>0){t.l.r=yield* splay(t.l.r,v,idx);if(t.l.r)t.l=left(t.l);}yield* aux();return t.l?right(t):t;}if(diff>0){if(!t.r)return t;const d=yield* valueCompare(v,t.r.v,idx,t.r.idx);if(d>0){t.r.r=yield* splay(t.r.r,v,idx);t=left(t);}else if(d<0){t.r.l=yield* splay(t.r.l,v,idx);if(t.r.l)t.r=right(t.r);}yield* aux();return t.r?left(t):t;}return t;}
for(let i=0;i<n;i++){const node={v:a[i],idx:i,l:null,r:null,h:1,priority:r()};nodes.push(node);if(c.tree==='Splay'&&root){root=yield* splay(root,node.v,i);if((yield* valueCompare(node.v,root.v,i,root.idx))<0){node.l=root.l;node.r=root;root.l=null;}else{node.r=root.r;node.l=root;root.r=null;}root=node;yield* aux();}else root=yield* insert(root,node);}let k=0;function* walk(t){if(!t)return;yield* walk(t.l);yield* write(k++,t.v);yield* walk(t.r);}yield* walk(root);}
function* msd(lo,hi,power){if(hi-lo<2||power<1)return;const base=c.base,lists=Array.from({length:base},()=>[]);for(let i=lo;i<hi;i++){lists[Math.floor(a[i]/power)%base].push(a[i]);yield* aux();}let k=lo;for(const list of lists){const start=k;for(const v of list)yield* write(k++,v);yield* msd(start,k,Math.floor(power/base));}}
function* american(lo,hi,power){if(hi-lo<2||power<1)return;const base=c.base,count=Array(base).fill(0);for(let i=lo;i<hi;i++){count[Math.floor(a[i]/power)%base]++;yield* aux();}const start=[lo];for(let b=0;b<base;b++)start.push(start[b]+count[b]);const next=start.slice();for(let b=0;b<base;b++)while(next[b]<start[b+1]){const digit=Math.floor(a[next[b]]/power)%base;if(digit===b){next[b]++;yield* aux();}else yield* swap(next[b],next[digit]++);}for(let b=0;b<base;b++)yield* american(start[b],start[b+1],Math.floor(power/base));}
function* bitonic(lo,len,up){if(len<2)return;const h=len/2;yield* bitonic(lo,h,true);yield* bitonic(lo+h,h,false);yield* bitmerge(lo,len,up);}function* bitmerge(lo,len,up){if(len<2)return;const h=len/2;for(let i=lo;i<lo+h;i++){const d=yield* compare(i,i+h);if(up?d>0:d<0)yield* swap(i,i+h);}yield* bitmerge(lo,h,up);yield* bitmerge(lo+h,h,up);}
function* oddMerge(lo,len,stride){const step=stride*2;if(step<len){yield* oddMerge(lo,len,step);yield* oddMerge(lo+stride,len,step);for(let i=lo+stride;i+stride<lo+len;i+=step)if((yield* compare(i,i+stride))>0)yield* swap(i,i+stride);}else if((yield* compare(lo,lo+stride))>0)yield* swap(lo,lo+stride);}function* network(lo,len){if(len<2)return;const h=len/2;yield* network(lo,h);yield* network(lo+h,h);yield* oddMerge(lo,len,1);}
function* stooge(lo,hi){if((yield* compare(lo,hi))>0)yield* swap(lo,hi);if(hi-lo>1){const t=Math.floor((hi-lo+1)/3);yield* stooge(lo,hi-t);yield* stooge(lo+t,hi);yield* stooge(lo,hi-t);}}
function* slow(lo,hi){if(lo>=hi)return;const m=(lo+hi)>>1;yield* slow(lo,m);yield* slow(m+1,hi);if((yield* compare(m,hi))>0)yield* swap(m,hi);yield* slow(lo,hi-1);}
function* ordered(len=n){for(let i=1;i<len;i++)if((yield* compare(i-1,i))>0)return false;return true;}function* shuffle(len=n){for(let i=len-1;i>0;i--)yield* swap(i,Math.floor(r()*(i+1)));}
function* bogobogo(len){if(len<=1)return;while(true){yield* bogobogo(len-1);if(yield* ordered(len))return;yield* shuffle(len);}}
function* run(){switch(entry.family){case 'Bubble':{function* pass(end){if(end<=0)return;let changed=false;if(c.reverse){for(let i=n-1;i>=n-end;i--)if((yield* compare(i-1,i))>0){yield* swap(i-1,i);changed=true;}}else for(let i=0;i<end;i++)if((yield* compare(i,i+1))>0){yield* swap(i,i+1);changed=true;}if(c.early&&!changed)return;if(c.recursive)yield* pass(end-1);}if(c.recursive)yield* pass(n-1);else for(let e=n-1;e>0;e--){let changed=false;if(c.reverse){for(let i=n-1;i>=n-e;i--)if((yield* compare(i-1,i))>0){yield* swap(i-1,i);changed=true;}}else for(let i=0;i<e;i++)if((yield* compare(i,i+1))>0){yield* swap(i,i+1);changed=true;}if(c.early&&!changed)break;}break;}
case 'Cocktail':{let l=0,h=n-1;while(l<h){let changed=false;for(let i=l;i<h;i++)if((yield* compare(i,i+1))>0){yield* swap(i,i+1);changed=true;}h--;if(c.early&&!changed)break;changed=false;for(let i=h;i>l;i--)if((yield* compare(i-1,i))>0){yield* swap(i-1,i);changed=true;}l++;if(c.early&&!changed)break;}break;}
case 'Comb':{let gap=n,changed=true;while(gap>1||changed){gap=Math.max(1,Math.floor(gap/c.gap));changed=false;for(let i=0;i+gap<n;i++)if((yield* compare(i,i+gap))>0){yield* swap(i,i+gap);changed=true;}}break;}
case 'Gnome':{let i=1,next=2;while(i<n){if(i===0||(yield* compare(i-1,i))<=0){if(c.smart){i=next;next++;}else i++;}else{yield* swap(i-1,i);i--;}}break;}
case 'Odd-even':{let changed=true;while(changed){changed=false;for(const parity of c.even?[0,1]:[1,0])for(let i=parity;i<n-1;i+=2)if((yield* compare(i,i+1))>0){yield* swap(i,i+1);changed=true;}}break;}
case 'Selection':{if(c.double){let l=0,h=n-1;while(l<h){let min=l,max=l;for(let i=l+1;i<=h;i++){if((yield* compare(i,min))<0)min=i;if((yield* compare(i,max))>0)max=i;}yield* swap(l,min);if(max===l)max=min;yield* swap(h,max);l++;h--;}}else for(let i=0;i<n-1;i++){let min=i;for(let j=i+1;j<n;j++)if((yield* compare(j,min))<0)min=j;if(c.stable){const v=a[min];for(let j=min;j>i;j--)yield* write(j,a[j-1]);yield* write(i,v);}else yield* swap(i,min);}break;}
case 'Cycle':{for(let start=0;start<n-1;start++){let item=a[start],pos=start;for(let i=start+1;i<n;i++)if((yield* valueCompare(a[i],item,i,start))<0)pos++;if(pos===start)continue;while((yield* valueCompare(item,a[pos],start,pos))===0)pos++;let tmp=a[pos];yield* write(pos,item);item=tmp;while(pos!==start){pos=start;for(let i=start+1;i<n;i++)if((yield* valueCompare(a[i],item,i,start))<0)pos++;while((yield* valueCompare(item,a[pos],start,pos))===0)pos++;tmp=a[pos];yield* write(pos,item);item=tmp;}}break;}
case 'Insertion':{if(c.reverse){for(let i=n-2;i>=0;i--){const v=a[i];let j=i+1;while(j<n&&(yield* valueCompare(a[j],v,j,i))<0){yield* write(j-1,a[j]);j++;}yield* write(j-1,v);}}else if(c.recursive){function* rec(hi){if(hi<2)return;yield* rec(hi-1);const v=a[hi-1];let j=hi-2;while(j>=0&&(yield* valueCompare(a[j],v,j,hi-1))>0){yield* write(j+1,a[j]);j--;}yield* write(j+1,v);}yield* rec(n);}else yield* insertion();break;}
case 'Shell':{let gaps=[];switch(c.sequence){case 'Shell':for(let g=n>>1;g;g>>=1)gaps.push(g);break;case 'Odd halves':for(let g=n>>1;g;g=Math.floor(g/2))gaps.push(g%2?g:g+1);break;case 'Hibbard':for(let k=1;2**k-1<n;k++)gaps.push(2**k-1);break;case 'Knuth':for(let g=1;g<n;g=g*3+1)gaps.push(g);break;case 'Ciura':gaps=[1,4,10,23,57,132,301,701];break;case 'Tokuda':for(let k=1;k<20;k++){const g=Math.ceil((9*(9/4)**(k-1)-4)/5);if(g<n)gaps.push(g);}break;case 'Pratt':for(let x=1;x<n;x*=2)for(let y=x;y<n;y*=3)gaps.push(y);break;case 'Sedgewick':for(let k=0;k<10;k++)gaps.push(k%2===0?9*2**k-9*2**(k/2)+1:8*2**k-6*2**((k+1)/2)+1);break;case 'Powers of 3':for(let g=1;g<n;g*=3)gaps.push(g);break;case 'Fibonacci':{let x=1,y=2;while(x<n){gaps.push(x);[x,y]=[y,x+y];}break;}}gaps=[...new Set([1,...gaps])].filter(g=>g<n).sort((a,b)=>b-a);for(const gap of gaps)yield* insertion(0,n,gap);break;}
case 'Tree':yield* treeSort();break;
case 'Patience':{const piles=[];for(let i=0;i<n;i++){const v=a[i];let l=0,h=piles.length;while(l<h){const m=(l+h)>>1;if((yield* valueCompare(piles[m].at(-1),v,-1,i))>=0)h=m;else l=m+1;}if(l===piles.length)piles.push([]);piles[l].push(v);yield* aux();}let k=0;while(k<n){let best=-1;for(let j=0;j<piles.length;j++)if(piles[j].length&&(best<0||(yield* valueCompare(piles[j].at(-1),piles[best].at(-1)))<0))best=j;yield* write(k++,piles[best].pop());}break;}
case 'Quick':yield* quick(0,n-1);break;
case 'Merge':{if(c.bottom){for(let len=1;len<n;len*=2)for(let lo=0;lo+len<n;lo+=2*len)yield* mergeSegments([lo,lo+len,Math.min(n,lo+2*len)]);}else if(c.natural){let runs=[];for(let i=0;i<n;){const start=i++;while(i<n&&(yield* compare(i-1,i))<=0)i++;runs.push([start,i]);}while(runs.length>1){const next=[];for(let i=0;i<runs.length;i+=2){if(i+1<runs.length){yield* mergeSegments([runs[i][0],runs[i][1],runs[i+1][1]]);next.push([runs[i][0],runs[i+1][1]]);}else next.push(runs[i]);}runs=next;}}else yield* merge(0,n);break;}
case 'Heap':yield* heap();break;
case 'Strand':{let rest=a.slice(),out=[];while(rest.length){const strand=[rest.shift()],next=[];yield* aux();for(const v of rest){if((yield* valueCompare(v,strand.at(-1)))>=0)strand.push(v);else next.push(v);yield* aux();}rest=next;let i=0,j=0,merged=[];while(i<out.length&&j<strand.length){if((yield* valueCompare(out[i],strand[j]))<=0)merged.push(out[i++]);else merged.push(strand[j++]);yield* aux();}merged=merged.concat(out.slice(i),strand.slice(j));out=merged;for(let k=0;k<out.length;k++)yield* write(k,out[k]);}break;}
case 'Pigeonhole':{const holes=Array.from({length:100},()=>[]);for(let i=0;i<n;i++){holes[a[i]].push(a[i]);yield* aux();}let k=0;for(const hole of holes){yield* aux();for(const v of hole)yield* write(k++,v);}break;}
case 'Tournament':{const values=a.slice(),tree=Array(2*n).fill(-1);function* winner(x,y){if(x<0)return y;if(y<0)return x;return (yield* valueCompare(values[x],values[y],x,y))<=0?x:y;}for(let i=0;i<n;i++){tree[n+i]=i;yield* aux();}for(let i=n-1;i>0;i--){tree[i]=yield* winner(tree[2*i],tree[2*i+1]);yield* aux();}for(let k=0;k<n;k++){const idx=tree[1];yield* write(k,values[idx]);let p=n+idx;tree[p]=-1;yield* aux();while((p>>=1)>0){tree[p]=yield* winner(tree[p*2],tree[p*2+1]);yield* aux();}}break;}
case 'Counting':{const count=Array(100).fill(0);for(let i=0;i<n;i++){count[a[i]]++;yield* aux();}let k=0;for(let v=0;v<100;v++){yield* aux();while(count[v]-->0)yield* write(k++,v);}break;}
case 'Bucket':{const bins=Array.from({length:c.buckets},()=>[]);for(let i=0;i<n;i++){bins[Math.floor(a[i]*c.buckets/100)].push(a[i]);yield* aux();}let k=0;for(const bin of bins){for(let i=1;i<bin.length;i++){const v=bin[i];let j=i-1;while(j>=0&&(yield* valueCompare(bin[j],v))>0){bin[j+1]=bin[j];yield* aux();j--;}bin[j+1]=v;yield* aux();}for(const v of bin)yield* write(k++,v);}break;}
case 'Radix':{let power=1;while(power*c.base<=99)power*=c.base;if(c.msd)yield* msd(0,n,power);else for(let p=1;p<=99;p*=c.base){const bins=Array.from({length:c.base},()=>[]);for(let i=0;i<n;i++){bins[Math.floor(a[i]/p)%c.base].push(a[i]);yield* aux();}let k=0;for(const bin of bins)for(const v of bin)yield* write(k++,v);}break;}
case 'American flag':{let power=1;while(power*c.base<=99)power*=c.base;yield* american(0,n,power);break;}
case 'Bead':{const rows=Array.from({length:n},()=>Array(99).fill(0));for(let i=0;i<n;i++)for(let j=0;j<a[i];j++){rows[i][j]=1;yield* aux();}for(let j=0;j<99;j++){let count=0;for(let i=0;i<n;i++){count+=rows[i][j];rows[i][j]=0;yield* aux();}for(let i=n-count;i<n;i++){rows[i][j]=1;yield* aux();}}for(let i=0;i<n;i++)yield* write(i,rows[i].reduce((a,b)=>a+b,0));break;}
case 'Bitonic':yield* bitonic(0,n,true);break;case 'Network':yield* network(0,n);break;
case 'Pancake':for(let end=n-1;end>0;end--){let max=0;for(let i=1;i<=end;i++)if((yield* compare(i,max))>0)max=i;if(max!==end){if(max>0)yield* flip(max);yield* flip(end);}}break;
case 'Stooge':yield* stooge(0,n-1);break;case 'Slow':yield* slow(0,n-1);break;
case 'Bogo':while(!(yield* ordered()))yield* shuffle();break;
case 'Random swap':while(!(yield* ordered())){let i=Math.floor(r()*n),j=Math.floor(r()*n);yield* swap(i,j);}break;
case 'Bogobogo':yield* bogobogo(n);break;
} s.done=true;s.active=[];return s;}
const iterator=run();return{entry,state:s,step(){if(s.done||s.capped||s.error)return;try{const next=iterator.next();if(next.done){s.done=true;s.active=[];if(s.a.some((v,i)=>i&&s.a[i-1]>v))s.error='Validation failed';}else if(s.ops>=limit){s.capped=true;s.active=[];}}catch(e){s.error=e.message;s.active=[];}},iterator};}
return{catalog,input,racer,random};})();
if(typeof module!=='undefined')module.exports=ChaosSort;
