'use strict';
const AO = (()=>{
 function rng(seed){let a=seed>>>0;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
 const W=21,H=15,N=W*H,S=W+1,G=N-W-2;
 function neighbors(i){const x=i%W,y=Math.floor(i/W);return [[x+1,y],[x,y+1],[x-1,y],[x,y-1]].filter(([a,b])=>a>=0&&b>=0&&a<W&&b<H).map(([a,b])=>b*W+a);}
 function map(seed,preset){const r=rng(seed),grid=Array(N).fill(1);for(let y=0;y<H;y++)for(let x=0;x<W;x++){let i=y*W+x;if(x===0||y===0||x===W-1||y===H-1)grid[i]=0;else if(preset==='open')grid[i]=1;else if(preset==='mud')grid[i]=r()<.3?5:1;else if(preset==='zigzag')grid[i]=(x%4===0&&y!==(x%8===0?2:H-3))?0:1;else grid[i]=r()<.29?0:1;}
 // A safe route keeps generated random arenas playable. User edits may remove it.
 if(preset==='random'){for(let x=1;x<W-1;x++)grid[W+x]=1;for(let y=1;y<H-1;y++)grid[y*W+W-2]=1;}grid[S]=grid[G]=1;return grid;}
 const heuristic=i=>Math.abs(i%W-G%W)+Math.abs(Math.floor(i/W)-Math.floor(G/W));
 function search(grid,kind){const state={visited:[],path:[],cost:null,done:false,frontier:1};const dist=Array(N).fill(Infinity),parent=Array(N).fill(-1),seen=new Set(),queued=new Set([S]);dist[S]=0;const q=[S];
 function* run(){while(q.length){let idx=kind==='DFS'?q.length-1:0;if(kind==='Dijkstra'||kind==='A*')for(let j=1;j<q.length;j++)if(dist[q[j]]+(kind==='A*'?heuristic(q[j]):0)<dist[q[idx]]+(kind==='A*'?heuristic(q[idx]):0))idx=j;const u=q.splice(idx,1)[0];queued.delete(u);if(seen.has(u))continue;seen.add(u);state.visited.push(u);state.frontier=q.length;if(u===G){let p=G;while(p!==-1){state.path.unshift(p);p=parent[p];}state.cost=dist[G];yield state;break;}for(const v of neighbors(u)){if(!grid[v]||seen.has(v))continue;const d=dist[u]+grid[v];if(kind==='BFS'||kind==='DFS'){if(dist[v]!==Infinity)continue;dist[v]=d;parent[v]=u;q.push(v);queued.add(v);}else if(d<dist[v]){dist[v]=d;parent[v]=u;if(!queued.has(v)){q.push(v);queued.add(v);}}}state.frontier=q.length;yield state;}state.done=true;return state;}
 return {state,iterator:run()};}
 function array(seed,pattern,size=48){const r=rng(seed),a=Array.from({length:size},()=>1+Math.floor(r()*99));if(pattern==='reverse')a.sort((a,b)=>b-a);if(pattern==='almost'){a.sort((a,b)=>a-b);for(let i=0;i<4;i++){let x=Math.floor(r()*size),y=Math.floor(r()*size);[a[x],a[y]]=[a[y],a[x]];}}if(pattern==='duplicates')for(let i=0;i<size;i++)a[i]=(a[i]%5+1)*18;return a;}
 function sort(input,kind){const a=[...input],state={a,active:[],comparisons:0,writes:0,ops:0,done:false};function* compare(i,j){state.comparisons++;state.ops++;state.active=[i,j];yield state;}function* swap(i,j){[a[i],a[j]]=[a[j],a[i]];state.writes+=2;state.ops++;state.active=[i,j];yield state;}function* write(i,v){a[i]=v;state.writes++;state.ops++;state.active=[i];yield state;}
 function* quick(lo,hi){if(lo>=hi)return;const pivot=a[hi];let k=lo;for(let i=lo;i<hi;i++){yield* compare(i,hi);if(a[i]<pivot){if(i!==k)yield* swap(i,k);k++;}}if(k!==hi)yield* swap(k,hi);yield* quick(lo,k-1);yield* quick(k+1,hi);}
 function* merge(lo,hi){if(hi-lo<=1)return;const mid=(lo+hi)>>1;yield* merge(lo,mid);yield* merge(mid,hi);let i=lo,j=mid,tmp=[];while(i<mid&&j<hi){yield* compare(i,j);tmp.push(a[i]<=a[j]?a[i++]:a[j++]);}while(i<mid)tmp.push(a[i++]);while(j<hi)tmp.push(a[j++]);for(let k=0;k<tmp.length;k++)yield* write(lo+k,tmp[k]);}
 function* run(){if(kind==='Bubble'){for(let end=a.length-1;end>0;end--){let changed=false;for(let i=0;i<end;i++){yield* compare(i,i+1);if(a[i]>a[i+1]){yield* swap(i,i+1);changed=true;}}if(!changed)break;}}else if(kind==='Insertion'){for(let i=1;i<a.length;i++){const v=a[i];let j=i-1;while(j>=0){yield* compare(j,i);if(a[j]<=v)break;yield* write(j+1,a[j]);j--;}yield* write(j+1,v);}}else if(kind==='Quick')yield* quick(0,a.length-1);else yield* merge(0,a.length);state.done=true;state.active=[];return state;}
 return{state,iterator:run()};}
 function resources(seed){const r=rng(seed),a=Array(N).fill(0);for(let i=0;i<N;i++)if(i%W>0&&i%W<W-1&&Math.floor(i/W)>0&&Math.floor(i/W)<H-1&&r()<.16)a[i]=1+Math.floor(r()*5);a[S]=0;return a;}
 function hunt(input,kind,seed){const a=[...input],r=rng(seed),state={a,pos:S,score:0,tick:0,trail:[S],done:false,target:-1};const distance=(a,b)=>Math.abs(a%W-b%W)+Math.abs(Math.floor(a/W)-Math.floor(b/W));let prev=-1;
 function* run(){while(state.tick<180){let options=[];for(let i=0;i<N;i++)if(a[i])options.push(i);if(!options.length)break;let next;const valid=neighbors(state.pos).filter(i=>i%W>0&&i%W<W-1&&Math.floor(i/W)>0&&Math.floor(i/W)<H-1);if(kind==='Random'){const choices=valid.filter(i=>i!==prev);next=choices[Math.floor(r()*choices.length)];state.target=-1;}else{let target=options[0],best=-Infinity;for(const i of options){const d=Math.max(1,distance(state.pos,i));let utility=kind==='Nearest'?-d:kind==='Value greedy'?a[i]/d:(a[i]+options.filter(j=>distance(i,j)<=3).reduce((s,j)=>s+a[j]*.35,0))/d;if(utility>best){best=utility;target=i;}}state.target=target;next=valid.reduce((best,i)=>distance(i,target)<distance(best,target)?i:best,valid[0]);}prev=state.pos;state.pos=next;state.tick++;state.trail.push(next);if(a[next]){state.score+=a[next];a[next]=0;}yield state;}state.done=true;return state;}
 return{state,iterator:run()};}
 return{rng,W,H,N,S,G,neighbors,map,search,array,sort,resources,hunt};
})();
if(typeof module!=='undefined')module.exports=AO;
