'use strict';
(()=>{const $=id=>document.getElementById(id),C=LolzSort,wall=$('wall'),ctx=wall.getContext('2d'),families=[...new Set(C.catalog.map(e=>e.family))];const colors=['#d0fb80','#b3a0ff','#ffb177','#70d9f2','#f290bd','#f2d77f','#8ad5a6','#d0a3ff'];const total=C.catalog.length;let input,racers,running=false,round=0,frameTime=0,drawTime=0,selected=0,hover=-1,rankings=[];const expected=()=>input.slice().sort((a,b)=>a-b);let reference=[];
$('inspect').innerHTML=C.catalog.map(e=>`<option value="${e.id}">${String(e.id+1).padStart(3,'0')} · ${e.name}</option>`).join('');$('family').innerHTML+=families.map(f=>`<option>${f}</option>`).join('');$('roster').innerHTML=C.catalog.map(e=>`<div>${String(e.id+1).padStart(3,'0')} · ${e.name} <span>— ${e.family}</span><p>${e.note}</p></div>`).join('');
function live(r){return !r.state.done&&!r.state.capped&&!r.state.error;}function seed(){return Number($('seed').value)>>>0;}function build(newInput=true){running=false;round=0;frameTime=0;if(newInput)input=C.input(seed(),Number($('size').value),$('pattern').value);reference=expected();racers=C.catalog.map(e=>C.racer(e,input,seed(),Number($('budget').value)));rankings=[];$('start').disabled=false;$('step').disabled=false;$('start').textContent='▶ RELEASE THE SORTS';$('race-state').textContent='READY FOR CHAOS';$('commentary').textContent='The Bro Council has called an emergency sorting meeting.';draw();}
function bars(context,state,x,y,w,h,color){const gap=w/state.a.length;for(let i=0;i<state.a.length;i++){const v=state.a[i];context.fillStyle=state.active.includes(i)?'#ffffff':color;context.fillRect(x+i*gap+.5,y+h-v/100*h,Math.max(.5,gap-1),v/100*h);}}
function status(r){return r.state.error?'ERROR':r.state.done?'VERIFIED':r.state.capped?'BUDGET STOP':running?'RACING':round?'PAUSED':'READY';}
function view(){const p=Number($('view').value);return p<0?{cols:10,rows:10,start:0,count:total}:{cols:5,rows:5,start:p*25,count:25};}
function resizeWall(){const v=view();wall.width=v.cols*160;wall.height=v.rows*100;$('arena').style.setProperty('--ratio',String(wall.width/wall.height));}
function drawWall(){const v=view(),width=wall.width,height=wall.height,cw=width/v.cols,ch=height/v.rows,highlight=$('family').value;ctx.clearRect(0,0,width,height);for(let slot=0;slot<v.count;slot++){const i=v.start+slot,r=racers[i],s=r.state,x=slot%v.cols*cw,y=Math.floor(slot/v.cols)*ch,color=colors[families.indexOf(r.entry.family)%colors.length];ctx.globalAlpha=highlight==='all'||highlight===r.entry.family?1:.22;ctx.fillStyle=s.done?'#16231c':s.capped?'#251c19':'#141a27';ctx.fillRect(x+3,y+3,cw-6,ch-6);ctx.strokeStyle=i===hover?'#ffffff':s.done?'#d0fb8044':'#283045';ctx.strokeRect(x+3.5,y+3.5,cw-7,ch-7);ctx.fillStyle=s.done?'#d0fb80':color;ctx.fillRect(x+4,y+4,3,ch-8);ctx.font='bold 11px Arial';ctx.textAlign='left';let name=r.entry.name;if(ctx.measureText(name).width>cw-22){while(ctx.measureText(name+'…').width>cw-22)name=name.slice(0,-1);name+='…';}ctx.fillStyle='#e8ecf5';ctx.fillText(name,x+13,y+18);bars(ctx,s,x+12,y+28,cw-24,ch-48,color);ctx.font='9px monospace';ctx.fillStyle=s.capped?'#ffb177':s.done?'#d0fb80':'#99a8c4';ctx.fillText(status(r),x+12,y+ch-10);ctx.textAlign='right';ctx.fillStyle='#b6c0d1';ctx.fillText(s.ops.toLocaleString(),x+cw-12,y+ch-10);}ctx.globalAlpha=1;}
function detail(){if(!$('detail').open)return;const r=racers[selected],s=r.state;$('detail-family').textContent=String(selected+1).padStart(3,'0')+' / '+r.entry.family+' / '+status(r);$('detail-name').textContent=r.entry.name;$('detail-note').textContent=r.entry.note;const c=$('detail-canvas').getContext('2d');c.clearRect(0,0,1000,380);bars(c,s,15,20,970,340,colors[families.indexOf(r.entry.family)%colors.length]);$('detail-stats').innerHTML=`<span>OPERATIONS<b>${s.ops.toLocaleString()}</b></span><span>COMPARISONS<b>${s.comparisons.toLocaleString()}</b></span><span>MAIN-ARRAY WRITES<b>${s.writes.toLocaleString()}</b></span><span>CURRENT STAGE<b>${s.phase}</b></span><span>GROUPS<b>${s.groups}</b></span><span>RESULT<b>${status(r)}</b></span>`;}
function draw(){drawWall();const done=racers.filter(r=>r.state.done&&!r.state.error),capped=racers.filter(r=>r.state.capped).length;rankings=done.sort((a,b)=>a.state.ops-b.state.ops||a.entry.id-b.entry.id);$('finished').innerHTML=done.length+'<span>/ '+total+'</span>';$('tick').textContent=round.toLocaleString()+' synchronized rounds';$('wall-status').textContent=`${racers.filter(live).length} active · ${capped} budget stops`;const seen=new Set(),podiumRacers=$('podium-mode').value==='all'?rankings:rankings.filter(r=>{if(seen.has(r.entry.family))return false;seen.add(r.entry.family);return true;});$('podium').innerHTML=rankings.length?podiumRacers.slice(0,8).map((r,i)=>`<div class="podium-row"><b>${podiumRacers.filter(x=>x.state.ops<r.state.ops).length+1}</b><span>${r.entry.name}</span><small>${r.state.ops.toLocaleString()} ops</small></div>`).join(''):'<div class="empty">No verified finish yet. Give the athletes a moment.</div>';detail();}
function step(count=1){for(let k=0;k<count;k++){if(!racers.some(live))break;for(const r of racers)if(live(r)){r.step();if(r.state.done&&r.state.finish===null){r.state.finish=round+1;if(r.state.a.some((v,i)=>v!==reference[i]))r.state.error='Output differs from original input';}}round++;}if(!racers.some(live)){running=false;$('start').disabled=true;$('step').disabled=true;$('start').textContent='RACE COMPLETE';$('race-state').textContent='ALL RACERS FINISHED OR STOPPED';const capped=racers.filter(r=>r.state.capped).length;$('commentary').textContent=capped?`${capped} racers hit the budget. They are not finishers. Their medals remain imaginary.`:'Everyone finished. The chaos has briefly become order.';}else if(round>1000)$('commentary').textContent='The podium is filling up. The Bro Council is still debating procedure.';}
$('start').onclick=()=>{running=!running;$('start').textContent=running?'Ⅱ PAUSE THE CHAOS':'▶ RESUME THE CHAOS';$('race-state').textContent=running?total+' ENGINES / RACE IN PROGRESS':'PAUSED';draw();};$('step').onclick=()=>{running=false;$('start').textContent='▶ RESUME THE CHAOS';$('race-state').textContent='SINGLE STEP';step();draw();};$('replay').onclick=()=>build(false);$('shuffle').onclick=()=>{$('seed').value=(seed()+1)>>>0;build(true);};for(const id of ['seed','size','pattern'])$(id).onchange=()=>build(true);$('budget').onchange=()=>build(false);$('family').onchange=draw;$('podium-mode').onchange=draw;$('view').onchange=()=>{resizeWall();draw();};$('roster-search').oninput=()=>{const q=$('roster-search').value.toLowerCase();$('roster').innerHTML=C.catalog.filter(e=>(e.name+' '+e.family+' '+e.note).toLowerCase().includes(q)).map(e=>`<div>${String(e.id+1).padStart(3,'0')} · ${e.name} — ${e.family}<p>${e.note}</p></div>`).join('')||'No matches.';};function open(i){selected=i;$('inspect').value=String(i);if(!$('detail').open)$('detail').showModal();detail();}$('inspect-button').onclick=()=>open(Number($('inspect').value));$('close').onclick=()=>$('detail').close();$('previous').onclick=()=>open((selected+total-1)%total);$('next').onclick=()=>open((selected+1)%total);$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const b=$('detail').getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)$('detail').close();}});
function tile(e){const b=wall.getBoundingClientRect(),v=view(),x=Math.min(v.cols-1,Math.max(0,Math.floor((e.clientX-b.left)/b.width*v.cols))),y=Math.min(v.rows-1,Math.max(0,Math.floor((e.clientY-b.top)/b.height*v.rows)));return Math.min(total-1,v.start+y*v.cols+x);}wall.onpointermove=e=>{hover=tile(e);if(!running)drawWall();};wall.onpointerleave=()=>{hover=-1;if(!running)drawWall();};wall.onclick=e=>open(tile(e));wall.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open(Number($('inspect').value));}};function expand(on){$('arena').classList.toggle('expanded',on);$('leave-arena').hidden=!on;} $('fullscreen').onclick=()=>expand(true);$('leave-arena').onclick=()=>expand(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')expand(false);});

function frame(time){if(running&&time-frameTime>=33){frameTime=time;step(Number($('speed').value));}if(time-drawTime>=100&&(running||frameTime)){drawTime=time;draw();if(!running)frameTime=0;}requestAnimationFrame(frame);}resizeWall();build();requestAnimationFrame(frame);})();
