const assert=require('node:assert/strict'),AO=require('./engine.js');
function finish(r){for(let i=0;i<20000;i++){const n=r.iterator.next();if(n.done)return r.state;}throw Error('Did not terminate');}
for(let seed=0;seed<40;seed++){for(const preset of ['random','zigzag','mud','open']){const map=AO.map(seed,preset),d=finish(AO.search(map,'Dijkstra')),a=finish(AO.search(map,'A*'));assert.ok(d.path.length);assert.equal(a.cost,d.cost);for(const kind of ['BFS','DFS'])assert.ok(finish(AO.search(map,kind)).path.length);for(const s of [a,d]){assert.equal(s.path[0],AO.S);assert.equal(s.path.at(-1),AO.G);assert.equal(s.cost,s.path.slice(1).reduce((n,i)=>n+map[i],0));for(let j=1;j<s.path.length;j++)assert.ok(AO.neighbors(s.path[j-1]).includes(s.path[j]));}}
for(const pattern of ['random','reverse','almost','duplicates']){const arr=AO.array(seed,pattern),expected=[...arr].sort((a,b)=>a-b);for(const kind of ['Bubble','Insertion','Quick','Merge'])assert.deepEqual(finish(AO.sort(arr,kind)).a,expected);}
for(const kind of ['Nearest','Value greedy','Cluster scout','Random']){const arr=AO.resources(seed),s=finish(AO.hunt(arr,kind,seed));assert.equal(s.score,arr.reduce((a,b)=>a+b,0)-s.a.reduce((a,b)=>a+b,0));assert.ok(s.tick<=180);for(let j=1;j<s.trail.length;j++)assert.ok(AO.neighbors(s.trail[j-1]).includes(s.trail[j]));}}
const blocked=Array(AO.N).fill(0);blocked[AO.S]=blocked[AO.G]=1;for(const kind of ['BFS','DFS','Dijkstra','A*'])assert.equal(finish(AO.search(blocked,kind)).path.length,0);
assert.deepEqual(AO.map(1337,'random'),AO.map(1337,'random'));console.log('Passed: 40 seeds, valid paths, A*/Dijkstra costs, all sorting patterns, harvest conservation, unreachable maps.');

const signatures=new Set();for(let seed=0;seed<500;seed++){const map=AO.map(seed,'random'),s=finish(AO.search(map,'BFS'));assert.ok(s.path.length>31,'Random arena must require a detour');const topRight=[...Array(AO.W-2)].map((_,x)=>AO.W+x+1).concat([...Array(AO.H-2)].map((_,y)=>(y+1)*AO.W+AO.W-2));const leftBottom=[...Array(AO.H-2)].map((_,y)=>(y+1)*AO.W+1).concat([...Array(AO.W-2)].map((_,x)=>(AO.H-2)*AO.W+x+1));assert.ok(topRight.some(i=>!map[i]));assert.ok(leftBottom.some(i=>!map[i]));signatures.add(s.path.join(','));}assert.ok(signatures.size>450);console.log('Passed: 500 random arenas are connected, require detours, block both edge shortcuts, and have diverse routes.');
